# Generated by Django 4.1.7 on 2023-05-05 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod', models.CharField(default='Random desc', max_length=50)),
                ('category', models.CharField(default='dairy', max_length=50)),
                ('desc', models.CharField(default='Random desc', max_length=50)),
                ('price', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('createdTime', models.DateTimeField(auto_now=True)),
                ('productImage', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
            ],
        ),
    ]
