# Generated by Django 4.1.7 on 2023-05-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod',
            field=models.CharField(default='Random prod', max_length=50),
        ),
    ]
